languageCode = "zh-CN"
languageName = "简体中文"
languageDirection = "ltr"
weight = 1

title = "DisposableMemory - 一次性记忆"
copyright = "© driver1998，以 [CC-BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 授权"

[params]
dateFormat = "2006年1月2日"

# mainSections = ["section1", "section2"]
# description = "My awesome website"

[params.author]
name = "driver1998"
headline = "It works, what now?"
links = [
  { email = "mailto:driver1998.ms@outlook.com" },
  { bilibili = "https://space.bilibili.com/102484203" },
  { github = "https://github.com/username" },
  { x-twitter = "https://twitter.com/driver1998" },
]
